---
- hosts: all
  gather_facts: False
  become: yes
  tasks:
    - name: enable passwordless sudo for the ops group
      copy: 
        content: |
          %{{ group.ops.name }} ALL=(ALL:ALL) NOPASSWD:ALL
        dest: /etc/sudoers.d/ops
        validate: visudo -cf %s
        mode: 0440
